global:
  scrape_interval: 15s
  evaluation_interval: 15s
 
scrape_configs:
  - job_name: engine
    static_configs:
      - targets: ["engine:9091"]
    metrics_path: /metrics
  - job_name: table-manager
    static_configs:
      - targets: ["table-manager:9191"]
    metrics_path: /metrics
  - job_name: auth-service
    static_configs:
      - targets: ["auth-service:9291"]
    metrics_path: /metrics
  - job_name: wallet-service
    static_configs:
      - targets: ["wallet-service:9391"]
    metrics_path: /metrics
 
