FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o bin/migrator ./cmd/migrator

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/bin/migrator ./bin/migrator
COPY migrations ./migrations
COPY config ./config

CMD ["./bin/migrator", "-config", "/app/config/config.yaml"]
